// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Photosoil.Service.Data;

#nullable disable

namespace Photosoil.Service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240630140201_57")]
    partial class _57
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorEcoSystem", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("integer");

                    b.Property<int>("EcoSystemsId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorsId", "EcoSystemsId");

                    b.HasIndex("EcoSystemsId");

                    b.ToTable("AuthorEcoSystem");
                });

            modelBuilder.Entity("AuthorSoilObject", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("integer");

                    b.Property<int>("SoilObjectsId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorsId", "SoilObjectsId");

                    b.HasIndex("SoilObjectsId");

                    b.ToTable("AuthorSoilObject");
                });

            modelBuilder.Entity("EcoSystemFile", b =>
                {
                    b.Property<int>("EcoSystemsId")
                        .HasColumnType("integer");

                    b.Property<int>("ObjectPhotoId")
                        .HasColumnType("integer");

                    b.HasKey("EcoSystemsId", "ObjectPhotoId");

                    b.HasIndex("ObjectPhotoId");

                    b.ToTable("EcoSystemFile");
                });

            modelBuilder.Entity("EcoSystemPublication", b =>
                {
                    b.Property<int>("EcoSystemsId")
                        .HasColumnType("integer");

                    b.Property<int>("PublicationsId")
                        .HasColumnType("integer");

                    b.HasKey("EcoSystemsId", "PublicationsId");

                    b.HasIndex("PublicationsId");

                    b.ToTable("EcoSystemPublication");
                });

            modelBuilder.Entity("EcoSystemSoilObject", b =>
                {
                    b.Property<int>("EcoSystemsId")
                        .HasColumnType("integer");

                    b.Property<int>("SoilObjectsId")
                        .HasColumnType("integer");

                    b.HasKey("EcoSystemsId", "SoilObjectsId");

                    b.HasIndex("SoilObjectsId");

                    b.ToTable("EcoSystemSoilObject");
                });

            modelBuilder.Entity("FileSoilObject", b =>
                {
                    b.Property<int>("ObjectPhotoId")
                        .HasColumnType("integer");

                    b.Property<int>("SoilObjectsId")
                        .HasColumnType("integer");

                    b.HasKey("ObjectPhotoId", "SoilObjectsId");

                    b.HasIndex("SoilObjectsId");

                    b.ToTable("FileSoilObject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Photosoil.Core.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("RefreshToken");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Photosoil.Core.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacts")
                        .HasColumnType("text");

                    b.Property<int>("DataEngId")
                        .HasColumnType("integer");

                    b.Property<int>("DataRuId")
                        .HasColumnType("integer");

                    b.Property<string>("OtherProfiles")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataEngId");

                    b.HasIndex("DataRuId");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Photosoil.Core.Models.EcoSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longtitude")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("EcoSystem");
                });

            modelBuilder.Entity("Photosoil.Core.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEng")
                        .HasColumnType("text");

                    b.Property<string>("TitleRu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Authors")
                        .HasColumnType("text");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Doi")
                        .HasColumnType("text");

                    b.Property<string>("Edition")
                        .HasColumnType("text");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OtherLangId")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("Publication");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMulti")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMulti = true,
                            Name = "Отделы почв по Классификации почв России 2004/2008"
                        },
                        new
                        {
                            Id = 4,
                            IsMulti = true,
                            Name = "Природная зона"
                        },
                        new
                        {
                            Id = 2,
                            IsMulti = true,
                            Name = "Подтипы почв по Классификации почв России 2004/2008"
                        },
                        new
                        {
                            Id = 3,
                            IsMulti = true,
                            Name = "Типы почв по Классификации почв России 2004/2008"
                        },
                        new
                        {
                            Id = 5,
                            IsMulti = true,
                            Name = "Основные квалификаторы (WRB 2014)"
                        });
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.EcoTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EcoSystemId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsEnglish")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EcoSystemId");

                    b.ToTable("EcoTranslations");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.SoilTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedSoilComponents")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("GeographicLocation")
                        .HasColumnType("text");

                    b.Property<bool?>("IsEnglish")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlantCommunity")
                        .HasColumnType("text");

                    b.Property<string>("ReliefLocation")
                        .HasColumnType("text");

                    b.Property<string>("SoilFeatures")
                        .HasColumnType("text");

                    b.Property<int?>("SoilId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SoilId");

                    b.ToTable("SoilTranslations");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("Term");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassificationId = 5,
                            Name = "Cambric"
                        },
                        new
                        {
                            Id = 2,
                            ClassificationId = 5,
                            Name = "Chronic"
                        },
                        new
                        {
                            Id = 3,
                            ClassificationId = 5,
                            Name = "Titanic"
                        },
                        new
                        {
                            Id = 4,
                            ClassificationId = 5,
                            Name = "Gleyic"
                        },
                        new
                        {
                            Id = 5,
                            ClassificationId = 5,
                            Name = "Gleyic"
                        },
                        new
                        {
                            Id = 6,
                            ClassificationId = 5,
                            Name = "Orthofluvent"
                        },
                        new
                        {
                            Id = 7,
                            ClassificationId = 5,
                            Name = "Argillic"
                        },
                        new
                        {
                            Id = 8,
                            ClassificationId = 5,
                            Name = "Reductic_glycemic"
                        },
                        new
                        {
                            Id = 9,
                            ClassificationId = 5,
                            Name = "Rudic"
                        },
                        new
                        {
                            Id = 10,
                            ClassificationId = 5,
                            Name = "Somerc"
                        },
                        new
                        {
                            Id = 11,
                            ClassificationId = 5,
                            Name = "Polic"
                        },
                        new
                        {
                            Id = 12,
                            ClassificationId = 5,
                            Name = "Paralithic"
                        },
                        new
                        {
                            Id = 13,
                            ClassificationId = 5,
                            Name = "Ironpan"
                        },
                        new
                        {
                            Id = 14,
                            ClassificationId = 5,
                            Name = "Stagnic"
                        },
                        new
                        {
                            Id = 15,
                            ClassificationId = 5,
                            Name = "Steinic"
                        },
                        new
                        {
                            Id = 16,
                            ClassificationId = 5,
                            Name = "Natic"
                        },
                        new
                        {
                            Id = 17,
                            ClassificationId = 5,
                            Name = "Petrocalcic"
                        },
                        new
                        {
                            Id = 18,
                            ClassificationId = 5,
                            Name = "Limnetic"
                        },
                        new
                        {
                            Id = 19,
                            ClassificationId = 5,
                            Name = "Alluvial"
                        },
                        new
                        {
                            Id = 20,
                            ClassificationId = 5,
                            Name = "Mollisol"
                        },
                        new
                        {
                            Id = 21,
                            ClassificationId = 5,
                            Name = "Turfic"
                        },
                        new
                        {
                            Id = 22,
                            ClassificationId = 5,
                            Name = "Umbraept"
                        },
                        new
                        {
                            Id = 23,
                            ClassificationId = 5,
                            Name = "Umbraept"
                        },
                        new
                        {
                            Id = 24,
                            ClassificationId = 5,
                            Name = "Vertic"
                        },
                        new
                        {
                            Id = 25,
                            ClassificationId = 5,
                            Name = "Vitrande"
                        },
                        new
                        {
                            Id = 26,
                            ClassificationId = 5,
                            Name = "Laminar"
                        },
                        new
                        {
                            Id = 27,
                            ClassificationId = 5,
                            Name = "Histosols"
                        },
                        new
                        {
                            Id = 28,
                            ClassificationId = 5,
                            Name = "Chernozem"
                        },
                        new
                        {
                            Id = 29,
                            ClassificationId = 5,
                            Name = "Circalitoral_Cryozem"
                        },
                        new
                        {
                            Id = 30,
                            ClassificationId = 5,
                            Name = "Distropic"
                        },
                        new
                        {
                            Id = 31,
                            ClassificationId = 5,
                            Name = "Calciorthid"
                        },
                        new
                        {
                            Id = 32,
                            ClassificationId = 5,
                            Name = "Calcic"
                        },
                        new
                        {
                            Id = 33,
                            ClassificationId = 5,
                            Name = "Aluminous"
                        },
                        new
                        {
                            Id = 34,
                            ClassificationId = 5,
                            Name = "Andosol"
                        },
                        new
                        {
                            Id = 35,
                            ClassificationId = 5,
                            Name = "Brunic"
                        },
                        new
                        {
                            Id = 36,
                            ClassificationId = 5,
                            Name = "Entectic"
                        },
                        new
                        {
                            Id = 37,
                            ClassificationId = 5,
                            Name = "Eutric"
                        },
                        new
                        {
                            Id = 38,
                            ClassificationId = 5,
                            Name = "Gleyic"
                        },
                        new
                        {
                            Id = 39,
                            ClassificationId = 5,
                            Name = "Glossic"
                        },
                        new
                        {
                            Id = 40,
                            ClassificationId = 5,
                            Name = "Gypseous"
                        },
                        new
                        {
                            Id = 41,
                            ClassificationId = 5,
                            Name = "Hydrosols"
                        },
                        new
                        {
                            Id = 42,
                            ClassificationId = 5,
                            Name = "Glaciomoraine"
                        },
                        new
                        {
                            Id = 43,
                            ClassificationId = 5,
                            Name = "Fragmental"
                        },
                        new
                        {
                            Id = 44,
                            ClassificationId = 5,
                            Name = "Fibrist"
                        },
                        new
                        {
                            Id = 45,
                            ClassificationId = 5,
                            Name = "Fluvisols"
                        },
                        new
                        {
                            Id = 46,
                            ClassificationId = 5,
                            Name = "Foliaceous"
                        },
                        new
                        {
                            Id = 47,
                            ClassificationId = 5,
                            Name = "Albic"
                        },
                        new
                        {
                            Id = 48,
                            ClassificationId = 3,
                            Name = "Абразёмы глинисто-иллювиированные"
                        },
                        new
                        {
                            Id = 49,
                            ClassificationId = 3,
                            Name = "Агроабразёмы"
                        },
                        new
                        {
                            Id = 50,
                            ClassificationId = 3,
                            Name = "Агродерново-подзолисто-глеевые"
                        },
                        new
                        {
                            Id = 51,
                            ClassificationId = 3,
                            Name = "Агродерново-подзолистые"
                        },
                        new
                        {
                            Id = 52,
                            ClassificationId = 3,
                            Name = "Агрозёмы"
                        },
                        new
                        {
                            Id = 53,
                            ClassificationId = 3,
                            Name = "Агроземы текстурно-карбонатные"
                        },
                        new
                        {
                            Id = 54,
                            ClassificationId = 3,
                            Name = "Агросолоди"
                        },
                        new
                        {
                            Id = 55,
                            ClassificationId = 3,
                            Name = "Агростратозем"
                        },
                        new
                        {
                            Id = 56,
                            ClassificationId = 3,
                            Name = "Агростратозёмы темногумусовые"
                        },
                        new
                        {
                            Id = 57,
                            ClassificationId = 3,
                            Name = "Агротёмно-серые"
                        },
                        new
                        {
                            Id = 58,
                            ClassificationId = 3,
                            Name = "Агротёмно-серые глеевые"
                        },
                        new
                        {
                            Id = 59,
                            ClassificationId = 3,
                            Name = "Агротёмно-серые метаморфические"
                        },
                        new
                        {
                            Id = 60,
                            ClassificationId = 3,
                            Name = "Агрочернозем текстурно-карбонатный"
                        },
                        new
                        {
                            Id = 61,
                            ClassificationId = 3,
                            Name = "Агрочерноземы"
                        },
                        new
                        {
                            Id = 62,
                            ClassificationId = 3,
                            Name = "Аллювиальные"
                        },
                        new
                        {
                            Id = 63,
                            ClassificationId = 3,
                            Name = "Аллювиальные гумусовые (дерновые)"
                        },
                        new
                        {
                            Id = 64,
                            ClassificationId = 3,
                            Name = "Аллювиальные гумусовые глеевые"
                        },
                        new
                        {
                            Id = 65,
                            ClassificationId = 3,
                            Name = "Аллювиальные перегнойно-глеевые"
                        },
                        new
                        {
                            Id = 66,
                            ClassificationId = 3,
                            Name = "Аллювиальные тёмногумусовые"
                        },
                        new
                        {
                            Id = 67,
                            ClassificationId = 3,
                            Name = "Аллювиальные тёмногумусовые глеевые"
                        },
                        new
                        {
                            Id = 68,
                            ClassificationId = 3,
                            Name = "Аллювиальные торфянно-глеевые"
                        },
                        new
                        {
                            Id = 69,
                            ClassificationId = 3,
                            Name = "Бурая (аридная)"
                        },
                        new
                        {
                            Id = 70,
                            ClassificationId = 3,
                            Name = "Бурозёмы"
                        },
                        new
                        {
                            Id = 71,
                            ClassificationId = 3,
                            Name = "Бурозёмы грубогумусовые"
                        },
                        new
                        {
                            Id = 72,
                            ClassificationId = 3,
                            Name = "Бурозёмы тёмногумусовые"
                        },
                        new
                        {
                            Id = 73,
                            ClassificationId = 3,
                            Name = "Глеезёмы"
                        },
                        new
                        {
                            Id = 74,
                            ClassificationId = 3,
                            Name = "Глееземы криометаморфические"
                        },
                        new
                        {
                            Id = 75,
                            ClassificationId = 3,
                            Name = "Гумусово-гидрометаморфические"
                        },
                        new
                        {
                            Id = 76,
                            ClassificationId = 3,
                            Name = "Дерново подзолы"
                        },
                        new
                        {
                            Id = 77,
                            ClassificationId = 3,
                            Name = "Дерново-брусно-подзолистые"
                        },
                        new
                        {
                            Id = 78,
                            ClassificationId = 3,
                            Name = "Дерново-криометаморфические"
                        },
                        new
                        {
                            Id = 79,
                            ClassificationId = 3,
                            Name = "Дерново-подбуры"
                        },
                        new
                        {
                            Id = 80,
                            ClassificationId = 3,
                            Name = "Дерново-подбуры глеевые"
                        },
                        new
                        {
                            Id = 81,
                            ClassificationId = 3,
                            Name = "Дерново-подбуры элювоземы"
                        },
                        new
                        {
                            Id = 82,
                            ClassificationId = 3,
                            Name = "Дерново-подзол-глеевые"
                        },
                        new
                        {
                            Id = 83,
                            ClassificationId = 3,
                            Name = "Дерново-подзолистые"
                        },
                        new
                        {
                            Id = 84,
                            ClassificationId = 3,
                            Name = "Дерново-подзолы глеевые"
                        },
                        new
                        {
                            Id = 85,
                            ClassificationId = 3,
                            Name = "Дерново-солоди"
                        },
                        new
                        {
                            Id = 86,
                            ClassificationId = 3,
                            Name = "Дерново-элювиально-метаморфические"
                        },
                        new
                        {
                            Id = 87,
                            ClassificationId = 3,
                            Name = "Дерново-элювозем"
                        },
                        new
                        {
                            Id = 88,
                            ClassificationId = 3,
                            Name = "Карбо-петрозём"
                        },
                        new
                        {
                            Id = 89,
                            ClassificationId = 3,
                            Name = "Каштановые"
                        },
                        new
                        {
                            Id = 90,
                            ClassificationId = 3,
                            Name = "Криогумусовые"
                        },
                        new
                        {
                            Id = 91,
                            ClassificationId = 3,
                            Name = "Криозёмы"
                        },
                        new
                        {
                            Id = 92,
                            ClassificationId = 3,
                            Name = "Криозёмы грубогумусовые"
                        },
                        new
                        {
                            Id = 93,
                            ClassificationId = 3,
                            Name = "Криометаморфические"
                        },
                        new
                        {
                            Id = 94,
                            ClassificationId = 3,
                            Name = "Криометаморфические грубогумусовые"
                        },
                        new
                        {
                            Id = 95,
                            ClassificationId = 3,
                            Name = "Литозем грубогумусовый"
                        },
                        new
                        {
                            Id = 96,
                            ClassificationId = 3,
                            Name = "Органо-ржавозёмы"
                        },
                        new
                        {
                            Id = 97,
                            ClassificationId = 3,
                            Name = "Охристые"
                        },
                        new
                        {
                            Id = 98,
                            ClassificationId = 3,
                            Name = "Палевые"
                        },
                        new
                        {
                            Id = 99,
                            ClassificationId = 3,
                            Name = "Пелозем"
                        },
                        new
                        {
                            Id = 100,
                            ClassificationId = 3,
                            Name = "Пелоземы гумусовые"
                        },
                        new
                        {
                            Id = 101,
                            ClassificationId = 3,
                            Name = "Перегнойно-глеевые"
                        },
                        new
                        {
                            Id = 102,
                            ClassificationId = 3,
                            Name = "Перегnoonно-криометаморфические"
                        },
                        new
                        {
                            Id = 103,
                            ClassificationId = 3,
                            Name = "Перегнойно-охристая"
                        },
                        new
                        {
                            Id = 104,
                            ClassificationId = 3,
                            Name = "Перегнойно-темногумусовые"
                        },
                        new
                        {
                            Id = 105,
                            ClassificationId = 3,
                            Name = "Перегнойные"
                        },
                        new
                        {
                            Id = 106,
                            ClassificationId = 3,
                            Name = "Петроземы"
                        },
                        new
                        {
                            Id = 107,
                            ClassificationId = 3,
                            Name = "Подбуры"
                        },
                        new
                        {
                            Id = 108,
                            ClassificationId = 3,
                            Name = "Подбуры глеевые"
                        },
                        new
                        {
                            Id = 109,
                            ClassificationId = 3,
                            Name = "Подзол-элювозёмы"
                        },
                        new
                        {
                            Id = 110,
                            ClassificationId = 3,
                            Name = "Подзолисто-глеевые"
                        },
                        new
                        {
                            Id = 111,
                            ClassificationId = 3,
                            Name = "Подзолистые"
                        },
                        new
                        {
                            Id = 112,
                            ClassificationId = 3,
                            Name = "Подзолы"
                        },
                        new
                        {
                            Id = 113,
                            ClassificationId = 3,
                            Name = "Подзолы глеевые"
                        },
                        new
                        {
                            Id = 114,
                            ClassificationId = 3,
                            Name = "Псаммоземы"
                        },
                        new
                        {
                            Id = 115,
                            ClassificationId = 3,
                            Name = "Ржавозёмы"
                        },
                        new
                        {
                            Id = 116,
                            ClassificationId = 3,
                            Name = "Ржавозёмы грубогумусовые"
                        },
                        new
                        {
                            Id = 117,
                            ClassificationId = 3,
                            Name = "Светлогумусовые"
                        },
                        new
                        {
                            Id = 118,
                            ClassificationId = 3,
                            Name = "Серая метаморфическая"
                        },
                        new
                        {
                            Id = 119,
                            ClassificationId = 3,
                            Name = "Серогумусовые (дерновые)"
                        },
                        new
                        {
                            Id = 120,
                            ClassificationId = 3,
                            Name = "Серые"
                        },
                        new
                        {
                            Id = 121,
                            ClassificationId = 3,
                            Name = "Слоисто-пепловые"
                        },
                        new
                        {
                            Id = 122,
                            ClassificationId = 3,
                            Name = "Солоди темногумусовые"
                        },
                        new
                        {
                            Id = 123,
                            ClassificationId = 3,
                            Name = "Солонцы светлые"
                        },
                        new
                        {
                            Id = 124,
                            ClassificationId = 3,
                            Name = "Солонцы темные"
                        },
                        new
                        {
                            Id = 125,
                            ClassificationId = 3,
                            Name = "Солончаки"
                        },
                        new
                        {
                            Id = 126,
                            ClassificationId = 3,
                            Name = "Солончаки глеевые"
                        },
                        new
                        {
                            Id = 127,
                            ClassificationId = 3,
                            Name = "Стратозёмы серогумусовые"
                        },
                        new
                        {
                            Id = 128,
                            ClassificationId = 3,
                            Name = "Сухо-торфяные"
                        },
                        new
                        {
                            Id = 129,
                            ClassificationId = 3,
                            Name = "Сухоторфяно-подбуры"
                        },
                        new
                        {
                            Id = 130,
                            ClassificationId = 3,
                            Name = "Сухоторфяно-подзолы"
                        },
                        new
                        {
                            Id = 131,
                            ClassificationId = 3,
                            Name = "Сухоторфяные"
                        },
                        new
                        {
                            Id = 132,
                            ClassificationId = 3,
                            Name = "Темно-серые"
                        },
                        new
                        {
                            Id = 133,
                            ClassificationId = 3,
                            Name = "Темно-серые глеевые"
                        },
                        new
                        {
                            Id = 134,
                            ClassificationId = 3,
                            Name = "Темно-serые метаморфические"
                        },
                        new
                        {
                            Id = 135,
                            ClassificationId = 3,
                            Name = "Темногумусово-глеевые"
                        },
                        new
                        {
                            Id = 136,
                            ClassificationId = 3,
                            Name = "Темногумусовые"
                        },
                        new
                        {
                            Id = 137,
                            ClassificationId = 3,
                            Name = "Темногумусовые подбелы"
                        },
                        new
                        {
                            Id = 138,
                            ClassificationId = 3,
                            Name = "Торфозёмы"
                        },
                        new
                        {
                            Id = 139,
                            ClassificationId = 3,
                            Name = "Торфяно-глеезёмы"
                        },
                        new
                        {
                            Id = 140,
                            ClassificationId = 3,
                            Name = "Торфяно-криозёмы"
                        },
                        new
                        {
                            Id = 141,
                            ClassificationId = 3,
                            Name = "Торфяно-подзолисто-глеевые"
                        },
                        new
                        {
                            Id = 142,
                            ClassificationId = 3,
                            Name = "Торфяно-подзолы"
                        },
                        new
                        {
                            Id = 143,
                            ClassificationId = 3,
                            Name = "Торфяно-подзолы глеевые"
                        },
                        new
                        {
                            Id = 144,
                            ClassificationId = 3,
                            Name = "Торфяные олиготрофные"
                        },
                        new
                        {
                            Id = 145,
                            ClassificationId = 3,
                            Name = "Торфяные олиготрофные глеевые"
                        },
                        new
                        {
                            Id = 146,
                            ClassificationId = 3,
                            Name = "Торфяные эутрофные"
                        },
                        new
                        {
                            Id = 147,
                            ClassificationId = 3,
                            Name = "Торфяные эутрофные глеевые"
                        },
                        new
                        {
                            Id = 148,
                            ClassificationId = 2,
                            Name = "Артииндустратный"
                        },
                        new
                        {
                            Id = 149,
                            ClassificationId = 2,
                            Name = "Глее-подзолистые"
                        },
                        new
                        {
                            Id = 150,
                            ClassificationId = 2,
                            Name = "Глееватые"
                        },
                        new
                        {
                            Id = 151,
                            ClassificationId = 2,
                            Name = "Глеевые"
                        },
                        new
                        {
                            Id = 152,
                            ClassificationId = 2,
                            Name = "Глинисто-иллювиированные"
                        },
                        new
                        {
                            Id = 153,
                            ClassificationId = 2,
                            Name = "Глинофибровые"
                        },
                        new
                        {
                            Id = 154,
                            ClassificationId = 2,
                            Name = "Грубо-гумусированные"
                        },
                        new
                        {
                            Id = 155,
                            ClassificationId = 2,
                            Name = "Гумусово-слаборазвитый"
                        },
                        new
                        {
                            Id = 156,
                            ClassificationId = 2,
                            Name = "Дисперсно-карбонатный"
                        },
                        new
                        {
                            Id = 157,
                            ClassificationId = 2,
                            Name = "Железисто-гранулированные (гранузёмы)"
                        },
                        new
                        {
                            Id = 158,
                            ClassificationId = 2,
                            Name = "Засоленные"
                        },
                        new
                        {
                            Id = 159,
                            ClassificationId = 2,
                            Name = "Иллювиально-гумусовые"
                        },
                        new
                        {
                            Id = 160,
                            ClassificationId = 2,
                            Name = "Иллювиально-железистые"
                        },
                        new
                        {
                            Id = 161,
                            ClassificationId = 2,
                            Name = "Иллювиально-ожелезненные"
                        },
                        new
                        {
                            Id = 162,
                            ClassificationId = 2,
                            Name = "Иллювиально-гумусированные"
                        },
                        new
                        {
                            Id = 163,
                            ClassificationId = 2,
                            Name = "Иловато-перегнойные"
                        },
                        new
                        {
                            Id = 164,
                            ClassificationId = 2,
                            Name = "Иловато-торфяные"
                        },
                        new
                        {
                            Id = 165,
                            ClassificationId = 2,
                            Name = "Квазиглееватые"
                        },
                        new
                        {
                            Id = 166,
                            ClassificationId = 2,
                            Name = "Конкреционные"
                        },
                        new
                        {
                            Id = 167,
                            ClassificationId = 2,
                            Name = "Контактно-осветленные"
                        },
                        new
                        {
                            Id = 168,
                            ClassificationId = 2,
                            Name = "Крио-гомогенные"
                        },
                        new
                        {
                            Id = 169,
                            ClassificationId = 2,
                            Name = "Криогенно-ожелезненные"
                        },
                        new
                        {
                            Id = 170,
                            ClassificationId = 2,
                            Name = "Криометаморфические"
                        },
                        new
                        {
                            Id = 171,
                            ClassificationId = 2,
                            Name = "Криотурбированные"
                        },
                        new
                        {
                            Id = 172,
                            ClassificationId = 2,
                            Name = "Мерзлотные"
                        },
                        new
                        {
                            Id = 173,
                            ClassificationId = 2,
                            Name = "Миграционно-мицелярный"
                        },
                        new
                        {
                            Id = 174,
                            ClassificationId = 2,
                            Name = "Миграционно-сегрегационные"
                        },
                        new
                        {
                            Id = 175,
                            ClassificationId = 2,
                            Name = "Минерально-торфяные"
                        },
                        new
                        {
                            Id = 176,
                            ClassificationId = 2,
                            Name = "Омергеленные"
                        },
                        new
                        {
                            Id = 177,
                            ClassificationId = 2,
                            Name = "Оподзоленные"
                        },
                        new
                        {
                            Id = 178,
                            ClassificationId = 2,
                            Name = "Оруденелые"
                        },
                        new
                        {
                            Id = 179,
                            ClassificationId = 2,
                            Name = "Осолоделые"
                        },
                        new
                        {
                            Id = 180,
                            ClassificationId = 2,
                            Name = "Остаточно-карбонатные"
                        },
                        new
                        {
                            Id = 181,
                            ClassificationId = 2,
                            Name = "Остаточно-эутрофные"
                        },
                        new
                        {
                            Id = 182,
                            ClassificationId = 2,
                            Name = "Палево-метаморфизованные"
                        },
                        new
                        {
                            Id = 183,
                            ClassificationId = 2,
                            Name = "Палево-подзолистые"
                        },
                        new
                        {
                            Id = 184,
                            ClassificationId = 2,
                            Name = "Палевые"
                        },
                        new
                        {
                            Id = 185,
                            ClassificationId = 2,
                            Name = "Перегнойно-грубогумусовые"
                        },
                        new
                        {
                            Id = 186,
                            ClassificationId = 2,
                            Name = "Перегнойно-торфяные"
                        },
                        new
                        {
                            Id = 187,
                            ClassificationId = 2,
                            Name = "Перегнойные"
                        },
                        new
                        {
                            Id = 188,
                            ClassificationId = 2,
                            Name = "Перегнойные (глеевые)"
                        },
                        new
                        {
                            Id = 189,
                            ClassificationId = 2,
                            Name = "Потечно-гумусовые"
                        },
                        new
                        {
                            Id = 190,
                            ClassificationId = 2,
                            Name = "Псевдофибровые"
                        },
                        new
                        {
                            Id = 191,
                            ClassificationId = 2,
                            Name = "С микропрофилем подзола"
                        },
                        new
                        {
                            Id = 192,
                            ClassificationId = 2,
                            Name = "Сегрегационные"
                        },
                        new
                        {
                            Id = 193,
                            ClassificationId = 2,
                            Name = "Со вторым гумусовым горизонтом"
                        },
                        new
                        {
                            Id = 194,
                            ClassificationId = 2,
                            Name = "Солонцеватые"
                        },
                        new
                        {
                            Id = 195,
                            ClassificationId = 2,
                            Name = "Языковатые"
                        },
                        new
                        {
                            Id = 196,
                            ClassificationId = 4,
                            Name = "Влажные экваториальные леса"
                        },
                        new
                        {
                            Id = 197,
                            ClassificationId = 4,
                            Name = "Горные территории с высотной поясностью"
                        },
                        new
                        {
                            Id = 198,
                            ClassificationId = 4,
                            Name = "Субтропические вечно-зеленые леса и кустарники"
                        },
                        new
                        {
                            Id = 199,
                            ClassificationId = 4,
                            Name = "Типичная тундра (подзона)"
                        },
                        new
                        {
                            Id = 200,
                            ClassificationId = 4,
                            Name = "Южная тундра (подзона)"
                        },
                        new
                        {
                            Id = 201,
                            ClassificationId = 4,
                            Name = "Лесотундра"
                        },
                        new
                        {
                            Id = 202,
                            ClassificationId = 4,
                            Name = "Северная тайга (подзона)"
                        },
                        new
                        {
                            Id = 203,
                            ClassificationId = 4,
                            Name = "Средняя тайга (подзона)"
                        },
                        new
                        {
                            Id = 204,
                            ClassificationId = 4,
                            Name = "Южная тайга"
                        },
                        new
                        {
                            Id = 205,
                            ClassificationId = 4,
                            Name = "Хвойно-широколиственные леса"
                        },
                        new
                        {
                            Id = 206,
                            ClassificationId = 4,
                            Name = "Широколиственные леса"
                        },
                        new
                        {
                            Id = 207,
                            ClassificationId = 4,
                            Name = "Подтайга (мелколиственно-светлохвойная или хвойно-широколиственная)"
                        },
                        new
                        {
                            Id = 208,
                            ClassificationId = 4,
                            Name = "Лесостепь"
                        },
                        new
                        {
                            Id = 209,
                            ClassificationId = 4,
                            Name = "Степь (подзоны луговых и настоящих степей)"
                        },
                        new
                        {
                            Id = 210,
                            ClassificationId = 4,
                            Name = "Сухая и опустыненная степь"
                        },
                        new
                        {
                            Id = 211,
                            ClassificationId = 4,
                            Name = "Полупустыни и пустыни"
                        },
                        new
                        {
                            Id = 212,
                            ClassificationId = 4,
                            Name = "Субтропических саванн и редколесий"
                        },
                        new
                        {
                            Id = 213,
                            ClassificationId = 1,
                            Name = "Торфяные почвы"
                        },
                        new
                        {
                            Id = 214,
                            ClassificationId = 1,
                            Name = "Турбозёмы"
                        },
                        new
                        {
                            Id = 215,
                            ClassificationId = 1,
                            Name = "Хемозёмы"
                        },
                        new
                        {
                            Id = 216,
                            ClassificationId = 1,
                            Name = "Торфозёмы"
                        },
                        new
                        {
                            Id = 217,
                            ClassificationId = 1,
                            Name = "Текстурно-дифференцированные почвы"
                        },
                        new
                        {
                            Id = 218,
                            ClassificationId = 1,
                            Name = "Стратозёмы"
                        },
                        new
                        {
                            Id = 219,
                            ClassificationId = 1,
                            Name = "Структурно-метаморфические почвы"
                        },
                        new
                        {
                            Id = 220,
                            ClassificationId = 1,
                            Name = "Химически-преобразованные"
                        },
                        new
                        {
                            Id = 221,
                            ClassificationId = 1,
                            Name = "Щелочно-глинисто-дифференцированные почвы"
                        },
                        new
                        {
                            Id = 222,
                            ClassificationId = 1,
                            Name = "Элювиальные почвы"
                        },
                        new
                        {
                            Id = 223,
                            ClassificationId = 1,
                            Name = "Слаборазвитые почвы"
                        },
                        new
                        {
                            Id = 224,
                            ClassificationId = 1,
                            Name = "Светлогумусовые аккумулятивно-карбонатные почвы"
                        },
                        new
                        {
                            Id = 225,
                            ClassificationId = 1,
                            Name = "Аллювиальные почвы"
                        },
                        new
                        {
                            Id = 226,
                            ClassificationId = 1,
                            Name = "Альфегумусовые почвы"
                        },
                        new
                        {
                            Id = 227,
                            ClassificationId = 1,
                            Name = "Вулканические почвы"
                        },
                        new
                        {
                            Id = 228,
                            ClassificationId = 1,
                            Name = "Аккумулятивно-гумусовые почвы"
                        },
                        new
                        {
                            Id = 229,
                            ClassificationId = 1,
                            Name = "Аквазёмы"
                        },
                        new
                        {
                            Id = 230,
                            ClassificationId = 1,
                            Name = "Агроабразёмы"
                        },
                        new
                        {
                            Id = 231,
                            ClassificationId = 1,
                            Name = "Агрозёмы"
                        },
                        new
                        {
                            Id = 232,
                            ClassificationId = 1,
                            Name = "Галоморфные почвы"
                        },
                        new
                        {
                            Id = 233,
                            ClassificationId = 1,
                            Name = "Гидрометаморфические почвы"
                        },
                        new
                        {
                            Id = 234,
                            ClassificationId = 1,
                            Name = "Литозёмы"
                        },
                        new
                        {
                            Id = 235,
                            ClassificationId = 1,
                            Name = "Органо-аккумулятивные почвы"
                        },
                        new
                        {
                            Id = 236,
                            ClassificationId = 1,
                            Name = "Палево-метаморфические почвы"
                        },
                        new
                        {
                            Id = 237,
                            ClassificationId = 1,
                            Name = "Криометаморфические почвы"
                        },
                        new
                        {
                            Id = 238,
                            ClassificationId = 1,
                            Name = "Криогенные почвы (Криозёмы)"
                        },
                        new
                        {
                            Id = 239,
                            ClassificationId = 1,
                            Name = "Глеевые почвы"
                        },
                        new
                        {
                            Id = 240,
                            ClassificationId = 1,
                            Name = "Железисто-метаморфические почвы"
                        },
                        new
                        {
                            Id = 241,
                            ClassificationId = 1,
                            Name = "Абразёмы"
                        });
                });

            modelBuilder.Entity("Photosoil.Core.Models.SoilObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longtitude")
                        .HasColumnType("text");

                    b.Property<int?>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<int?>("PhotoId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("SoilObjects");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("PublicationSoilObject", b =>
                {
                    b.Property<int>("PublicationsId")
                        .HasColumnType("integer");

                    b.Property<int>("SoilObjectsId")
                        .HasColumnType("integer");

                    b.HasKey("PublicationsId", "SoilObjectsId");

                    b.HasIndex("SoilObjectsId");

                    b.ToTable("PublicationSoilObject");
                });

            modelBuilder.Entity("SoilObjectTerm", b =>
                {
                    b.Property<int>("SoilObjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("TermsId")
                        .HasColumnType("integer");

                    b.HasKey("SoilObjectsId", "TermsId");

                    b.HasIndex("TermsId");

                    b.ToTable("SoilObjectTerm");
                });

            modelBuilder.Entity("AuthorEcoSystem", b =>
                {
                    b.HasOne("Photosoil.Core.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.EcoSystem", null)
                        .WithMany()
                        .HasForeignKey("EcoSystemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthorSoilObject", b =>
                {
                    b.HasOne("Photosoil.Core.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.SoilObject", null)
                        .WithMany()
                        .HasForeignKey("SoilObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoSystemFile", b =>
                {
                    b.HasOne("Photosoil.Core.Models.EcoSystem", null)
                        .WithMany()
                        .HasForeignKey("EcoSystemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.File", null)
                        .WithMany()
                        .HasForeignKey("ObjectPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoSystemPublication", b =>
                {
                    b.HasOne("Photosoil.Core.Models.EcoSystem", null)
                        .WithMany()
                        .HasForeignKey("EcoSystemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoSystemSoilObject", b =>
                {
                    b.HasOne("Photosoil.Core.Models.EcoSystem", null)
                        .WithMany()
                        .HasForeignKey("EcoSystemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.SoilObject", null)
                        .WithMany()
                        .HasForeignKey("SoilObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileSoilObject", b =>
                {
                    b.HasOne("Photosoil.Core.Models.File", null)
                        .WithMany()
                        .HasForeignKey("ObjectPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.SoilObject", null)
                        .WithMany()
                        .HasForeignKey("SoilObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Photosoil.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Photosoil.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Photosoil.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Photosoil.Core.Models.Article", b =>
                {
                    b.HasOne("Photosoil.Core.Models.File", "Photo")
                        .WithOne()
                        .HasForeignKey("Photosoil.Core.Models.Article", "PhotoId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Author", b =>
                {
                    b.HasOne("Photosoil.Core.Models.Translation", "DataEng")
                        .WithMany()
                        .HasForeignKey("DataEngId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.Translation", "DataRu")
                        .WithMany()
                        .HasForeignKey("DataRuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.File", "Photo")
                        .WithOne()
                        .HasForeignKey("Photosoil.Core.Models.Author", "PhotoId");

                    b.HasOne("Photosoil.Core.Models.ApplicationUser", "User")
                        .WithMany("Authors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("DataEng");

                    b.Navigation("DataRu");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photosoil.Core.Models.EcoSystem", b =>
                {
                    b.HasOne("Photosoil.Core.Models.File", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.ApplicationUser", "User")
                        .WithMany("EcoSystems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Publication", b =>
                {
                    b.HasOne("Photosoil.Core.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("Photosoil.Core.Models.ApplicationUser", "User")
                        .WithMany("Publications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.EcoTranslation", b =>
                {
                    b.HasOne("Photosoil.Core.Models.EcoSystem", "EcoSystem")
                        .WithMany("Translations")
                        .HasForeignKey("EcoSystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EcoSystem");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.SoilTranslation", b =>
                {
                    b.HasOne("Photosoil.Core.Models.SoilObject", "SoilObject")
                        .WithMany("Translations")
                        .HasForeignKey("SoilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SoilObject");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.Term", b =>
                {
                    b.HasOne("Photosoil.Core.Models.Second.Classification", "Classification")
                        .WithMany("Terms")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("Photosoil.Core.Models.SoilObject", b =>
                {
                    b.HasOne("Photosoil.Core.Models.File", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.ApplicationUser", "User")
                        .WithMany("SoilObjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSoilObject", b =>
                {
                    b.HasOne("Photosoil.Core.Models.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.SoilObject", null)
                        .WithMany()
                        .HasForeignKey("SoilObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoilObjectTerm", b =>
                {
                    b.HasOne("Photosoil.Core.Models.SoilObject", null)
                        .WithMany()
                        .HasForeignKey("SoilObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photosoil.Core.Models.Second.Term", null)
                        .WithMany()
                        .HasForeignKey("TermsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Photosoil.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("EcoSystems");

                    b.Navigation("Publications");

                    b.Navigation("SoilObjects");
                });

            modelBuilder.Entity("Photosoil.Core.Models.EcoSystem", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Photosoil.Core.Models.Second.Classification", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Photosoil.Core.Models.SoilObject", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
