//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesslog
    {
        public int aid { get; set; }
        public string sid { get; set; }
        public string title { get; set; }
        public string path { get; set; }
        public string url { get; set; }
        public string hostname { get; set; }
        public Nullable<long> uid { get; set; }
        public long timer { get; set; }
        public long timestamp { get; set; }
    }
}
