//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class actions
    {
        public string aid { get; set; }
        public string type { get; set; }
        public string callback { get; set; }
        public byte[] parameters { get; set; }
        public string label { get; set; }
    }
}
