//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        public int bid { get; set; }
        public string module { get; set; }
        public string delta { get; set; }
        public string theme { get; set; }
        public sbyte status { get; set; }
        public int weight { get; set; }
        public string region { get; set; }
        public sbyte custom { get; set; }
        public sbyte visibility { get; set; }
        public string pages { get; set; }
        public string title { get; set; }
        public sbyte cache { get; set; }
        public int i18n_mode { get; set; }
    }
}
