//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int cid { get; set; }
        public int pid { get; set; }
        public int nid { get; set; }
        public int uid { get; set; }
        public string subject { get; set; }
        public string hostname { get; set; }
        public int created { get; set; }
        public int changed { get; set; }
        public byte status { get; set; }
        public string thread { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public string homepage { get; set; }
        public string language { get; set; }
    }
}
