//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_translation_revision
    {
        public string entity_type { get; set; }
        public long entity_id { get; set; }
        public long revision_id { get; set; }
        public string language { get; set; }
        public string source { get; set; }
        public int uid { get; set; }
        public int status { get; set; }
        public int translate { get; set; }
        public int created { get; set; }
        public int changed { get; set; }
    }
}
