//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_data_field_image
    {
        public string entity_type { get; set; }
        public string bundle { get; set; }
        public sbyte deleted { get; set; }
        public long entity_id { get; set; }
        public Nullable<long> revision_id { get; set; }
        public string language { get; set; }
        public long delta { get; set; }
        public Nullable<long> field_image_fid { get; set; }
        public string field_image_alt { get; set; }
        public string field_image_title { get; set; }
        public Nullable<long> field_image_width { get; set; }
        public Nullable<long> field_image_height { get; set; }
    }
}
