//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_config_instance
    {
        public int id { get; set; }
        public int field_id { get; set; }
        public string field_name { get; set; }
        public string entity_type { get; set; }
        public string bundle { get; set; }
        public byte[] data { get; set; }
        public sbyte deleted { get; set; }
    }
}
