//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_data_field_location
    {
        public string entity_type { get; set; }
        public string bundle { get; set; }
        public sbyte deleted { get; set; }
        public long entity_id { get; set; }
        public Nullable<long> revision_id { get; set; }
        public string language { get; set; }
        public long delta { get; set; }
        public Nullable<double> field_location_lat { get; set; }
        public Nullable<double> field_location_lon { get; set; }
        public Nullable<int> field_location_map_width { get; set; }
        public Nullable<int> field_location_map_height { get; set; }
        public Nullable<int> field_location_zoom { get; set; }
        public string field_location_name { get; set; }
    }
}
