//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_config
    {
        public int id { get; set; }
        public string field_name { get; set; }
        public string type { get; set; }
        public string module { get; set; }
        public sbyte active { get; set; }
        public string storage_type { get; set; }
        public string storage_module { get; set; }
        public sbyte storage_active { get; set; }
        public sbyte locked { get; set; }
        public byte[] data { get; set; }
        public sbyte cardinality { get; set; }
        public sbyte translatable { get; set; }
        public sbyte deleted { get; set; }
    }
}
