//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_managed
    {
        public long fid { get; set; }
        public long uid { get; set; }
        public string filename { get; set; }
        public string uri { get; set; }
        public string filemime { get; set; }
        public decimal filesize { get; set; }
        public sbyte status { get; set; }
        public long timestamp { get; set; }
        public string type { get; set; }
    }
}
