//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GluceverDb : DbContext
    {
        public GluceverDb()
            : base("name=GluceverDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesslog> accesslog { get; set; }
        public virtual DbSet<actions> actions { get; set; }
        public virtual DbSet<authmap> authmap { get; set; }
        public virtual DbSet<batch> batch { get; set; }
        public virtual DbSet<block> block { get; set; }
        public virtual DbSet<block_custom> block_custom { get; set; }
        public virtual DbSet<block_node_type> block_node_type { get; set; }
        public virtual DbSet<block_role> block_role { get; set; }
        public virtual DbSet<blocked_ips> blocked_ips { get; set; }
        public virtual DbSet<cache> cache { get; set; }
        public virtual DbSet<cache_block> cache_block { get; set; }
        public virtual DbSet<cache_bootstrap> cache_bootstrap { get; set; }
        public virtual DbSet<cache_features> cache_features { get; set; }
        public virtual DbSet<cache_field> cache_field { get; set; }
        public virtual DbSet<cache_filter> cache_filter { get; set; }
        public virtual DbSet<cache_form> cache_form { get; set; }
        public virtual DbSet<cache_image> cache_image { get; set; }
        public virtual DbSet<cache_libraries> cache_libraries { get; set; }
        public virtual DbSet<cache_media_xml> cache_media_xml { get; set; }
        public virtual DbSet<cache_menu> cache_menu { get; set; }
        public virtual DbSet<cache_page> cache_page { get; set; }
        public virtual DbSet<cache_panels> cache_panels { get; set; }
        public virtual DbSet<cache_path> cache_path { get; set; }
        public virtual DbSet<cache_token> cache_token { get; set; }
        public virtual DbSet<cache_variable> cache_variable { get; set; }
        public virtual DbSet<cache_views> cache_views { get; set; }
        public virtual DbSet<cache_views_data> cache_views_data { get; set; }
        public virtual DbSet<ckeditor_input_format> ckeditor_input_format { get; set; }
        public virtual DbSet<ckeditor_settings> ckeditor_settings { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<ctools_css_cache> ctools_css_cache { get; set; }
        public virtual DbSet<ctools_object_cache> ctools_object_cache { get; set; }
        public virtual DbSet<date_format_locale> date_format_locale { get; set; }
        public virtual DbSet<date_format_type> date_format_type { get; set; }
        public virtual DbSet<date_formats> date_formats { get; set; }
        public virtual DbSet<entity_translation> entity_translation { get; set; }
        public virtual DbSet<entity_translation_revision> entity_translation_revision { get; set; }
        public virtual DbSet<field_collection_item> field_collection_item { get; set; }
        public virtual DbSet<field_collection_item_revision> field_collection_item_revision { get; set; }
        public virtual DbSet<field_config> field_config { get; set; }
        public virtual DbSet<field_config_instance> field_config_instance { get; set; }
        public virtual DbSet<field_data_body> field_data_body { get; set; }
        public virtual DbSet<field_data_comment_body> field_data_comment_body { get; set; }
        public virtual DbSet<field_data_field_0408rus> field_data_field_0408rus { get; set; }
        public virtual DbSet<field_data_field_0408rus_subtypes> field_data_field_0408rus_subtypes { get; set; }
        public virtual DbSet<field_data_field_0408rus_types> field_data_field_0408rus_types { get; set; }
        public virtual DbSet<field_data_field_author> field_data_field_author { get; set; }
        public virtual DbSet<field_data_field_author_pic> field_data_field_author_pic { get; set; }
        public virtual DbSet<field_data_field_code> field_data_field_code { get; set; }
        public virtual DbSet<field_data_field_comments> field_data_field_comments { get; set; }
        public virtual DbSet<field_data_field_contacts> field_data_field_contacts { get; set; }
        public virtual DbSet<field_data_field_element_type> field_data_field_element_type { get; set; }
        public virtual DbSet<field_data_field_env_zone> field_data_field_env_zone { get; set; }
        public virtual DbSet<field_data_field_file_image_alt_text> field_data_field_file_image_alt_text { get; set; }
        public virtual DbSet<field_data_field_file_image_title_text> field_data_field_file_image_title_text { get; set; }
        public virtual DbSet<field_data_field_flora> field_data_field_flora { get; set; }
        public virtual DbSet<field_data_field_flora_details> field_data_field_flora_details { get; set; }
        public virtual DbSet<field_data_field_flora_stuff> field_data_field_flora_stuff { get; set; }
        public virtual DbSet<field_data_field_image> field_data_field_image { get; set; }
        public virtual DbSet<field_data_field_location> field_data_field_location { get; set; }
        public virtual DbSet<field_data_field_main_wrb_14> field_data_field_main_wrb_14 { get; set; }
        public virtual DbSet<field_data_field_photos> field_data_field_photos { get; set; }
        public virtual DbSet<field_data_field_pic> field_data_field_pic { get; set; }
        public virtual DbSet<field_data_field_picture> field_data_field_picture { get; set; }
        public virtual DbSet<field_data_field_position> field_data_field_position { get; set; }
        public virtual DbSet<field_data_field_ref_wrb_14> field_data_field_ref_wrb_14 { get; set; }
        public virtual DbSet<field_data_field_relief_position> field_data_field_relief_position { get; set; }
        public virtual DbSet<field_data_field_tags> field_data_field_tags { get; set; }
        public virtual DbSet<field_data_field_v_url> field_data_field_v_url { get; set; }
        public virtual DbSet<field_data_field_video_tags> field_data_field_video_tags { get; set; }
        public virtual DbSet<field_revision_body> field_revision_body { get; set; }
        public virtual DbSet<field_revision_comment_body> field_revision_comment_body { get; set; }
        public virtual DbSet<field_revision_field_0408rus> field_revision_field_0408rus { get; set; }
        public virtual DbSet<field_revision_field_0408rus_subtypes> field_revision_field_0408rus_subtypes { get; set; }
        public virtual DbSet<field_revision_field_0408rus_types> field_revision_field_0408rus_types { get; set; }
        public virtual DbSet<field_revision_field_author> field_revision_field_author { get; set; }
        public virtual DbSet<field_revision_field_author_pic> field_revision_field_author_pic { get; set; }
        public virtual DbSet<field_revision_field_code> field_revision_field_code { get; set; }
        public virtual DbSet<field_revision_field_comments> field_revision_field_comments { get; set; }
        public virtual DbSet<field_revision_field_contacts> field_revision_field_contacts { get; set; }
        public virtual DbSet<field_revision_field_element_type> field_revision_field_element_type { get; set; }
        public virtual DbSet<field_revision_field_env_zone> field_revision_field_env_zone { get; set; }
        public virtual DbSet<field_revision_field_file_image_alt_text> field_revision_field_file_image_alt_text { get; set; }
        public virtual DbSet<field_revision_field_file_image_title_text> field_revision_field_file_image_title_text { get; set; }
        public virtual DbSet<field_revision_field_flora> field_revision_field_flora { get; set; }
        public virtual DbSet<field_revision_field_flora_details> field_revision_field_flora_details { get; set; }
        public virtual DbSet<field_revision_field_flora_stuff> field_revision_field_flora_stuff { get; set; }
        public virtual DbSet<field_revision_field_image> field_revision_field_image { get; set; }
        public virtual DbSet<field_revision_field_location> field_revision_field_location { get; set; }
        public virtual DbSet<field_revision_field_main_wrb_14> field_revision_field_main_wrb_14 { get; set; }
        public virtual DbSet<field_revision_field_photos> field_revision_field_photos { get; set; }
        public virtual DbSet<field_revision_field_pic> field_revision_field_pic { get; set; }
        public virtual DbSet<field_revision_field_picture> field_revision_field_picture { get; set; }
        public virtual DbSet<field_revision_field_position> field_revision_field_position { get; set; }
        public virtual DbSet<field_revision_field_ref_wrb_14> field_revision_field_ref_wrb_14 { get; set; }
        public virtual DbSet<field_revision_field_relief_position> field_revision_field_relief_position { get; set; }
        public virtual DbSet<field_revision_field_tags> field_revision_field_tags { get; set; }
        public virtual DbSet<field_revision_field_v_url> field_revision_field_v_url { get; set; }
        public virtual DbSet<field_revision_field_video_tags> field_revision_field_video_tags { get; set; }
        public virtual DbSet<file_display> file_display { get; set; }
        public virtual DbSet<file_managed> file_managed { get; set; }
        public virtual DbSet<file_metadata> file_metadata { get; set; }
        public virtual DbSet<file_type> file_type { get; set; }
        public virtual DbSet<file_usage> file_usage { get; set; }
        public virtual DbSet<filter> filter { get; set; }
        public virtual DbSet<filter_format> filter_format { get; set; }
        public virtual DbSet<flood> flood { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<i18n_block_language> i18n_block_language { get; set; }
        public virtual DbSet<i18n_path> i18n_path { get; set; }
        public virtual DbSet<i18n_string> i18n_string { get; set; }
        public virtual DbSet<i18n_translation_set> i18n_translation_set { get; set; }
        public virtual DbSet<image_effects> image_effects { get; set; }
        public virtual DbSet<image_styles> image_styles { get; set; }
        public virtual DbSet<languages> languages { get; set; }
        public virtual DbSet<locales_source> locales_source { get; set; }
        public virtual DbSet<locales_target> locales_target { get; set; }
        public virtual DbSet<media_filter_usage> media_filter_usage { get; set; }
        public virtual DbSet<media_list_type> media_list_type { get; set; }
        public virtual DbSet<media_type> media_type { get; set; }
        public virtual DbSet<menu_custom> menu_custom { get; set; }
        public virtual DbSet<menu_links> menu_links { get; set; }
        public virtual DbSet<menu_router> menu_router { get; set; }
        public virtual DbSet<node> node { get; set; }
        public virtual DbSet<node_access> node_access { get; set; }
        public virtual DbSet<node_comment_statistics> node_comment_statistics { get; set; }
        public virtual DbSet<node_counter> node_counter { get; set; }
        public virtual DbSet<node_revision> node_revision { get; set; }
        public virtual DbSet<node_type> node_type { get; set; }
        public virtual DbSet<object_log> object_log { get; set; }
        public virtual DbSet<panels_display> panels_display { get; set; }
        public virtual DbSet<panels_layout> panels_layout { get; set; }
        public virtual DbSet<panels_mini> panels_mini { get; set; }
        public virtual DbSet<panels_node> panels_node { get; set; }
        public virtual DbSet<panels_pane> panels_pane { get; set; }
        public virtual DbSet<panels_renderer_pipeline> panels_renderer_pipeline { get; set; }
        public virtual DbSet<pathauto_state> pathauto_state { get; set; }
        public virtual DbSet<queue> queue { get; set; }
        public virtual DbSet<rdf_mapping> rdf_mapping { get; set; }
        public virtual DbSet<registry> registry { get; set; }
        public virtual DbSet<registry_file> registry_file { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_permission> role_permission { get; set; }
        public virtual DbSet<search_dataset> search_dataset { get; set; }
        public virtual DbSet<search_index> search_index { get; set; }
        public virtual DbSet<search_node_links> search_node_links { get; set; }
        public virtual DbSet<search_total> search_total { get; set; }
        public virtual DbSet<semaphore> semaphore { get; set; }
        public virtual DbSet<sequences> sequences { get; set; }
        public virtual DbSet<sessions> sessions { get; set; }
        public virtual DbSet<shortcut_set> shortcut_set { get; set; }
        public virtual DbSet<shortcut_set_users> shortcut_set_users { get; set; }
        public virtual DbSet<stylizer> stylizer { get; set; }
        public virtual DbSet<system> system { get; set; }
        public virtual DbSet<taxonomy_term_data> taxonomy_term_data { get; set; }
        public virtual DbSet<taxonomy_term_hierarchy> taxonomy_term_hierarchy { get; set; }
        public virtual DbSet<taxonomy_vocabulary> taxonomy_vocabulary { get; set; }
        public virtual DbSet<url_alias> url_alias { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_roles> users_roles { get; set; }
        public virtual DbSet<variable> variable { get; set; }
        public virtual DbSet<variable_store> variable_store { get; set; }
        public virtual DbSet<views_display> views_display { get; set; }
        public virtual DbSet<views_view> views_view { get; set; }
        public virtual DbSet<watchdog> watchdog { get; set; }
        public virtual DbSet<taxonomy_index> taxonomy_index { get; set; }
    }
}
