//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class i18n_string
    {
        public int lid { get; set; }
        public string textgroup { get; set; }
        public string context { get; set; }
        public string objectid { get; set; }
        public string type { get; set; }
        public string property { get; set; }
        public int objectindex { get; set; }
        public string format { get; set; }
    }
}
