//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class i18n_translation_set
    {
        public long tsid { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public string bundle { get; set; }
        public long master_id { get; set; }
        public int status { get; set; }
        public int created { get; set; }
        public int changed { get; set; }
    }
}
