//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class languages
    {
        public string language { get; set; }
        public string name { get; set; }
        public string native { get; set; }
        public int direction { get; set; }
        public int enabled { get; set; }
        public int plurals { get; set; }
        public string formula { get; set; }
        public string domain { get; set; }
        public string prefix { get; set; }
        public int weight { get; set; }
        public string javascript { get; set; }
    }
}
