//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_target
    {
        public int lid { get; set; }
        public byte[] translation { get; set; }
        public string language { get; set; }
        public int plid { get; set; }
        public int plural { get; set; }
        public int i18n_status { get; set; }
    }
}
