//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_source
    {
        public int lid { get; set; }
        public string location { get; set; }
        public string textgroup { get; set; }
        public byte[] source { get; set; }
        public string context { get; set; }
        public string version { get; set; }
    }
}
