//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_type
    {
        public string name { get; set; }
        public string label { get; set; }
        public sbyte @base { get; set; }
        public int weight { get; set; }
        public string type_callback { get; set; }
        public string type_callback_args { get; set; }
    }
}
