//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_links
    {
        public string menu_name { get; set; }
        public long mlid { get; set; }
        public long plid { get; set; }
        public string link_path { get; set; }
        public string router_path { get; set; }
        public string link_title { get; set; }
        public byte[] options { get; set; }
        public string module { get; set; }
        public short hidden { get; set; }
        public short external { get; set; }
        public short has_children { get; set; }
        public short expanded { get; set; }
        public int weight { get; set; }
        public short depth { get; set; }
        public short customized { get; set; }
        public long p1 { get; set; }
        public long p2 { get; set; }
        public long p3 { get; set; }
        public long p4 { get; set; }
        public long p5 { get; set; }
        public long p6 { get; set; }
        public long p7 { get; set; }
        public long p8 { get; set; }
        public long p9 { get; set; }
        public short updated { get; set; }
        public string language { get; set; }
        public long i18n_tsid { get; set; }
    }
}
