//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_router
    {
        public string path { get; set; }
        public byte[] load_functions { get; set; }
        public byte[] to_arg_functions { get; set; }
        public string access_callback { get; set; }
        public byte[] access_arguments { get; set; }
        public string page_callback { get; set; }
        public byte[] page_arguments { get; set; }
        public string delivery_callback { get; set; }
        public int fit { get; set; }
        public short number_parts { get; set; }
        public int context { get; set; }
        public string tab_parent { get; set; }
        public string tab_root { get; set; }
        public string title { get; set; }
        public string title_callback { get; set; }
        public string title_arguments { get; set; }
        public string theme_callback { get; set; }
        public string theme_arguments { get; set; }
        public int type { get; set; }
        public string description { get; set; }
        public string position { get; set; }
        public int weight { get; set; }
        public string include_file { get; set; }
    }
}
