//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class node_comment_statistics
    {
        public long nid { get; set; }
        public int cid { get; set; }
        public int last_comment_timestamp { get; set; }
        public string last_comment_name { get; set; }
        public int last_comment_uid { get; set; }
        public long comment_count { get; set; }
    }
}
