//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class node_access
    {
        public long nid { get; set; }
        public long gid { get; set; }
        public string realm { get; set; }
        public byte grant_view { get; set; }
        public byte grant_update { get; set; }
        public byte grant_delete { get; set; }
    }
}
