//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        public long nid { get; set; }
        public Nullable<long> vid { get; set; }
        public string type { get; set; }
        public string language { get; set; }
        public string title { get; set; }
        public int uid { get; set; }
        public int status { get; set; }
        public int created { get; set; }
        public int changed { get; set; }
        public int comment { get; set; }
        public int promote { get; set; }
        public int sticky { get; set; }
        public long tnid { get; set; }
        public int translate { get; set; }
    }
}
