//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class node_type
    {
        public string type { get; set; }
        public string name { get; set; }
        public string @base { get; set; }
        public string module { get; set; }
        public string description { get; set; }
        public string help { get; set; }
        public byte has_title { get; set; }
        public string title_label { get; set; }
        public sbyte custom { get; set; }
        public sbyte modified { get; set; }
        public sbyte locked { get; set; }
        public sbyte disabled { get; set; }
        public string orig_type { get; set; }
    }
}
