//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class panels_display
    {
        public int did { get; set; }
        public string layout { get; set; }
        public string layout_settings { get; set; }
        public string panel_settings { get; set; }
        public string cache { get; set; }
        public string title { get; set; }
        public Nullable<sbyte> hide_title { get; set; }
        public Nullable<int> title_pane { get; set; }
        public Nullable<System.Guid> uuid { get; set; }
    }
}
