//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class panels_pane
    {
        public int pid { get; set; }
        public int did { get; set; }
        public string panel { get; set; }
        public string type { get; set; }
        public string subtype { get; set; }
        public Nullable<sbyte> shown { get; set; }
        public string access { get; set; }
        public string configuration { get; set; }
        public string cache { get; set; }
        public string style { get; set; }
        public string css { get; set; }
        public string extras { get; set; }
        public Nullable<short> position { get; set; }
        public string locks { get; set; }
        public Nullable<System.Guid> uuid { get; set; }
    }
}
