//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions
    {
        public long uid { get; set; }
        public string sid { get; set; }
        public string ssid { get; set; }
        public string hostname { get; set; }
        public int timestamp { get; set; }
        public int cache { get; set; }
        public byte[] session { get; set; }
    }
}
