//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class system
    {
        public string filename { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string owner { get; set; }
        public int status { get; set; }
        public int bootstrap { get; set; }
        public short schema_version { get; set; }
        public int weight { get; set; }
        public byte[] info { get; set; }
    }
}
