//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_vocabulary
    {
        public long vid { get; set; }
        public string name { get; set; }
        public string machine_name { get; set; }
        public string description { get; set; }
        public byte hierarchy { get; set; }
        public string module { get; set; }
        public int weight { get; set; }
        public string language { get; set; }
        public long i18n_mode { get; set; }
    }
}
