//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class views_display
    {
        public long vid { get; set; }
        public string id { get; set; }
        public string display_title { get; set; }
        public string display_plugin { get; set; }
        public Nullable<int> position { get; set; }
        public string display_options { get; set; }
    }
}
