//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class views_view
    {
        public long vid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string tag { get; set; }
        public string base_table { get; set; }
        public string human_name { get; set; }
        public Nullable<int> core { get; set; }
    }
}
