//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photosoil.Exporter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class watchdog
    {
        public int wid { get; set; }
        public int uid { get; set; }
        public string type { get; set; }
        public string message { get; set; }
        public byte[] variables { get; set; }
        public byte severity { get; set; }
        public string link { get; set; }
        public string location { get; set; }
        public string referer { get; set; }
        public string hostname { get; set; }
        public int timestamp { get; set; }
    }
}
